CREATE TABLE `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(20) NOT NULL UNIQUE,
    `name` VARCHAR(20) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `suspended` BOOLEAN NOT NULL DEFAULT FALSE,
    `terminated` BOOLEAN NOT NULL DEFAULT FALSE,
    `admin` BOOLEAN NOT NULL DEFAULT FALSE,
    `repo` INT NOT NULL DEFAULT 0,
    `issue` INT NOT NULL DEFAULT 0,
    `pr` INT NOT NULL DEFAULT 0
);
